python generate_histos_AB.py 0 preselection rootfiles/latest_production/MC/backgrounds/HPhiGammaAnalysis_Signal.root histos/latest_production/histos_SR_Signal.root
python generate_histos_AB.py 0 preselection rootfiles/latest_production/dataprocess/HPhiGammaAnalysis_Data.root histos/latest_production/histos_SR_Data.root
python generate_histos_AB.py 1 preselection rootfiles/latest_production/dataprocess/HPhiGammaAnalysis_Data.root histos/latest_production/histos_CR_Sidebands.root
